c2nim.nimble

`compiler#devel` doesn't work when not using latest devel Nim.

require less recent compiler (fixes #38)

---

cparse.nim
testsuite/results/bitfield.nim
testsuite/tests/bitfield.h

will close https://github.com/nim-lang/c2nim/issues/49
I'm emitting a `bitsize` pragma as @Varriount suggested, but it's currently showing up after the type instead of as part of it.
``` nim
type
bits* = object
flag*: cint
{.bitsize:1.}
opts*: cint
{.bitsize:4.}
```

Add support for bitfields

---

.gitignore
.travis.yml
c2nim.nim
c2nim.nimble
clex.nim
cparse.nim
cpp.nim
doc/c2nim.rst
rules.nim
testsuite/results/skipsection.nim
testsuite/tester.nim
testsuite/tests/skipsection.h

I have added a new directive (`#skip`) which can instruct c2nim to skip certain `#ifdef` blocks altogether.
In doing so, I have done some minor cleanup (removed some deprecation errors, and moved the nimble file to nimscript, while adding a `tests` task).

Added support for #skip directive

---

cparse.nim
testsuite/results/cpp11.nim
testsuite/tests/cpp11.cpp

c2nim can now parse this: `std::ostream &operator << (std::ostream &out, const Enum &t);`
It was failing to recognize a declaration due to the  `::` scope token.

Handle qualified return type in operator overload signature

---

.travis.yml
nim.cfg
testsuite/results/bug107_108.nim
testsuite/results/smartptrs.nim

1. c2nim has a couple case object transitions, use `-d:nimOldCaseObjects` until `c2nim/cparser` and `nim/ast` are updated.
2. type pragma placement changed.

[bugfix] update for 0.20.0

---

.gitignore
cparse.nim
testsuite/results/constructorcall.nim
testsuite/results/cpp11.nim
testsuite/tester.nim
testsuite/tests/constructorcall.cpp
testsuite/tests/cpp11.cpp
testsuite/tests/cpp11.hpp

Fixed #163 
Merge the constexpr PR first.

Skips C++11 List initializers in headers.

---

c2nim.nim
cparse.nim
testsuite/results/struct_directives.nim
testsuite/tests/struct_directives.h

When converting function types in .h, `{.noconv.}` can be added by this
options.
For example. Below is a C header file:
```C
// this declaration should be annotated with "noconv"
typedef int (*f_callback_funtion)(void *data, void *user_data);
// this is a function defined in C source
void register_callback(f_callback_funtion f, void *user_data);
```
If we want to define our callback function in nim, we can do it like this:
```nim
proc my_fun(data: pointer, user_data: pointer): cint {.exportc noconv.} = ...
register_callback(my_fun, nil)
```

add a new option: annotate procs with `{.noconv.}`

---

cparse.nim
testsuite/results/cpp11.nim
testsuite/tests/cpp11.hpp

This should fix  #165 by ignoring constructors with ` = delete;`

Implement deleted constructors (c++11)

---

cpp.nim
testsuite/results/directives.nim
testsuite/tests/directives.h

Below is a common pattern to create default values/configurations. It will be good to be recognized by `c2nim`.
```C
#ifndef ONE
#define ONE (1)
#endif
```
A test case is included in this PR.

allow #define X after #ifndef X.

---

testsuite/tests/matrix.cpp
testsuite/tests/smartptrs.cpp

No actual diffs. (`git diff -w`)
This PR is not a real change, so it can be merged immediately. That would help my rebasing for future PRs.
(If the repo has only `\n` line-endings, then people can get whatever they want by setting their `.gitconfig` properly.)

Fix line-endings (only ws changes)

---

c2nim.nim
cparse.nim
rules.nim

Added a command line option to annotate procs with `{.importc:"<origName>".}`
The `--header` command line option adds `importc` and `header` pragmas to types as well as procs, but I only want `importc` pragmas on the procs.

added --importc option

---

cparse.nim

When compiling union definitions generated by c2nim the compiler outputs the warning
```
Warning: type pragmas follow the type name; this form of writing pragmas is deprecated [Deprecated]
```
It's because the ``{.union.}`` pragma is added after the ``object`` keyword, e.g.
```
type MyUnion* {.bycopy.} = object {.union.}
value_one: int
value_two: float
```
This PR fixes it by inserting the pragma after the type name instead, e.g.
```
type MyUnion* {.bycopy, union.} = object
value_one: int
value_two: float
```
The ``isUnion`` argument is removed in procs that no longer need it. This includes ``proc parseTuple`` where it did not have any effect anyway.

fix warning about deprecated union pragmas

---

cparse.nim

If a C enum contains an alias, c2nim generates a constant, e.g.
```
typedef enum {
one = 1,
two = 2,
another_two = two,
three = 3
} my_enum;
```
becomes
```
type
my_enum* = enum
one = 1, two = 2, three = 3
const
another_two = two
```
Unfortunately that constant is not exported from the module. This PR fixes that.

export constants that are generated from enum aliases

---

clex.nim
cparse.nim

Parsing casted int64 constants greater than ``2^31 - 1`` does not work.
E.g. parsing the code
``` C
#define MY_MACRO ((uint64_t)2147483648)
```
will fail with this error message
```
Error: identifier expected, but got: (
```
This PR fixes that. It also calls ``parseBiggestInt`` instead of ``parseInt``. This should avoid problems on 32-bit architectures (not tested).

fix parsing casted int64 constants

---

cparse.nim

- oldClassOrig can be immutable
- line not needed: ``p.options.classes[p.currentClassOrig] = "true"``

small improvements in proc parseStandaloneClass

---

doc/c2nim.rst

Given
```c
void foo() {}
void foo_() {}
void foo__() {}
void __foo() {}
void __foo__() {}
void foo_bar_() {}
void foo_bar() {}
void _foo_bar_() {}
void foo() {}
void foo_() {}
void foo__() {}
void __foo() {}
void __foo__() {}
void foo_bar_() {}
void foo_bar() {}
void _foo_bar_() {}
void _____foo___var_asdfasdf_asdf_asdfa_() {}
void ______________asss____() {}
void ____s_____() {}
```
outputs 
```nim
proc foo*() =
discard
proc foo*() =
discard
proc foo*() =
discard
proc foo*() =
discard
proc foo*() =
discard
proc foo_bar*() =
discard
proc foo_bar*() =
discard
proc foo_bar*() =
discard
proc foo*() =
discard
proc foo*() =
discard
proc foo*() =
discard
proc foo*() =
discard
proc foo*() =
discard
proc foo_bar*() =
discard
proc foo_bar*() =
discard
proc foo_bar*() =
discard
proc …
```

Add `#mangle` example for fixing C identifiers (to conform nep1-style)

---

cparser.nim

Currently c2nim skips comments after a constant expression, at the end of an enum (without a comma):
```c
// Shader attribute data types
typedef enum {
SHADER_ATTRIB_FLOAT = 0,           // Shader attribute type: float
SHADER_ATTRIB_VEC2 = 1,            // Shader attribute type: vec2 (2 float)
SHADER_ATTRIB_VEC3 = 2,            // Shader attribute type: vec3 (3 float)
SHADER_ATTRIB_VEC4 =  3            // Shader attribute type: vec4 (4 float) <- warning: skipped comment ...
} ShaderAttributeDataType;
```
not sure if that's an acceptable solution but it can be extended for #define as well

Capture comments by providing the parent node

---

c2nim.nimble
nim.cfg

Bump minimal version requirements because deepcopy is only introduced since Nim 1.4.0
ref https://github.com/nim-lang/Nim/pull/19972

supports Arc/Orc by enabling deepcopy

---

compiler/msgs.nim

ref https://github.com/nim-lang/Nim/pull/19972
```
2022-07-28T11:12:09.4182108Z Downloading https://github.com/nim-lang/c2nim using git
2022-07-28T11:12:09.4182506Z   Verifying dependencies for c2nim@#head
2022-07-28T11:12:09.4182810Z  Installing c2nim@#head
2022-07-28T11:12:09.4183134Z    Building c2nim/c2nim using c backend
2022-07-28T11:12:09.4183913Z [1m/tmp/nimble_20270/githubcom_nimlangc2nim_#head/c2nim.nim(12, 16) [0m[33mWarning: [0mNumber of spaces around '/' is not consistent[36m [Spacing][0m[0m
2022-07-28T11:12:09.4184858Z [1m/tmp/nimble_20270/githubcom_nimlangc2nim_#head/compiler/llstream.nim(13, 3) [0m[33mWarning: [0mimported and not used: 'strutils'[36m [UnusedImport][0m[0m
2022-07-28T11:12:09.4186479Z [1m/tmp/nimble_20270/githubcom_nimlangc2nim_#head/compiler/o …
```

replace shallowCopy with move, otherwise it fails nimgen

---

c2nim.nim
compiler/renderer.nim
cparser.nim
nim.cfg
preprocessor.nim

Hey! Thanks for keeping `c2nim` up and working! 
I decided to take the time to fix/tweak a few things that I run into a lot and figure others might find them useful. 
- Importing C `#defines` macro functions as external C functions using `importc` pragma
- Import C `#defines` constants as external C var's using `importc`
- Add VARARGS support for `#define` macro functions supporting templates 
+ Note this doesn't create a proper macro to handle the varargs but it creates filler `args: seq[untyped]` 
- Add VARARGS support for  `#define` macro functions supporting C imports with `{.varargs.}` pragma
- Add command line option to pass mangle directives (useful for all those `uint8_t` types from `<stdint.h>`) 
I'll work on adding the test cases I'm using tomorrow. I haven't run the test suite …

Add varargs to defines, defines as C imports, and CLI mangle option

---

c2nim.nim
c2nim.nimble
cparser.nim
doc/c2nim.rst
testsuite/results/cppstatic.nim
testsuite/tester.nim
testsuite/tests/cppstatic.hpp

```cpp
class ClassA
{
public:
static void test();
};
```
Now becomes
```nim
proc test*(_: `type` ClassA) {.importcpp: "ClassA::test(@)",
header: "cppstatic.hpp".}
```
(notice the added `type ClassA` parameter)
which can be used by doing ClassA.test()

Better handling of CPP static methods

---

cparser.nim
doc/c2nim.rst
mangler.nim
preprocessor.nim
testsuite/cextras/rcl_allocator_imp_pragma.h
testsuite/results/rcl_allocator_imp_pragma.nim

``#clibuserpragma`` directive
---------------------
**Note**: There is also a ``--clibuserpragma`` command line option that can be used for
the same purpose.
This directive enables using a `clib` user definable pragma instead of a dynlib or 
header pragmas. This can be used with a user defined pragma to provide a way to
configure using a dynlib or a header import:
```nim
const rcutilsDynlib {.strdefine.}: string = ""
when rcutilsDynlib == "":
{.pragma: clib, header: "rcutils/cmdline_parser.h" .}
else:
{.pragma: clib, dynlib: "" & rcutilsDynlib.}
proc rcutils_get_zero_initialized_allocator*(): rcutils_allocator_t {.
importc: "rcutils_get_zero_initialized_allocator", clib.}
```

Add clib pragma for configurable dynlib vs header 
